### ISSUE TITLE
Use GitHub release after each CRAN update?

### ISSUE THREAD

**Issue by maelle** [ropensci/helminthR#25]
So that the rOpenSci newsletter might pick up the update. :-) (the next one, the one for today couldn't ropensci.org/blog/2021/03/16/ropensci-news)

**Comment by taddallas** [comment]
Definitely a good idea. Sorry for the long delay. I'll be submitting update to CRAN sometime in the next week or so, and will be sure to do a GitHub release. Thanks!

**Comment by maelle** [comment]
Yay! I'm planning to prepare the next newsletter for next week, so maybe the update will be picked up in the September rather than August newsletter. Good luck with the CRAN update!
